---
default:
  pipeline:
    Cloud-provider:
      - name: "Azure resource group name"
        key: azure_resource_group_name
        widget: simple_text
        type: string
        default: "cycloid-demo"
      - name: "Azure environment"
        key: azure_env
        widget: radios
        type: string
        values:
        - public
        - china
        - german
        - stack
        - usgovernment
        default: public
      - name: "Azure location"
        key: azure_location
        widget: auto_complete
        type: string
        values: [eastasia,southeastasia,centralus,eastus,eastus2,westus,northcentralus,southcentralus,northeurope,westeurope,japanwest,japaneast,brazilsouth,australiaeast,australiasoutheast,southindia,centralindia,westindia,canadacentral,canadaeast,uksouth,ukwest,westcentralus,westus2,koreacentral,koreasouth,francecentral,francesouth,australiacentral,australiacentral2,uaecentral,uaenorth,southafricanorth,southafricawest,switzerlandnorth,switzerlandwest,germanynorth,germanywestcentral,norwaywest,norwayeast]
        default: francecentral
      - name: "Azure subscription id"
        key: azure_subscription_id
        widget: cy_cred
        type: string
        default: "((azure_step-by-step.subscription_id))"
      - name: "Azure tenant id"
        key: azure_tenant_id
        widget: cy_cred
        type: string
        default: "((azure_step-by-step.tenant_id))"
      - name: "Azure client id"
        key: azure_client_id
        widget: cy_cred
        type: string
        default: "((azure_step-by-step.client_id))"
      - name: "Azure client secret"
        key: azure_client_secret
        widget: cy_cred
        type: string
        default: "((azure_step-by-step.client_secret))"
    Git:
      - name: "Gits ssh key"
        key: git_ssh_key
        widget: cy_cred
        type: string
        default: "((ssh_step-by-step.ssh_key))"
      - name: "Code git repository url"
        key: code_git_public_repository
        widget: simple_text
        type: string
        default: "https://github.com/talset/stacks"
      - name: "Code git repository branch"
        key: code_git_branch
        widget: simple_text
        type: string
        default: code
      - name: "Service catalog repository"
        key: git_repository
        widget: cy_scs
        type: string
        default: git@github.com:talset/stacks.git
      - name: "Service catalog branch"
        key: stack_git_branch
        widget: cy_branch
        type: string
        source: git_repository
        default: azure
      - name: "Config catalog branch"
        key: config_git_branch
        widget: cy_branch
        type: string
        source: git_repository
        default: config
    Terraform:
      - name: "Terraform Azure storage account name"
        key: terraform_storage_account_name
        widget: cy_cred
        type: string
        default: "((azure_storage_step-by-step.account_name))"
      - name: "Terraform Azure storage access key"
        key: terraform_storage_access_key
        widget: cy_cred
        type: string
        default: "((azure_storage_step-by-step.access_key))"
      - name: "Azure storage account name"
        key: azure_storage_account_name
        widget: simple_text
        type: string
        default: "cycloiddemotfstate"
      - name: "Azure storage container name"
        key: terraform_storage_container_name
        widget: simple_text
        type: string
        default: "cycloid-demo"
      - name: "Azure storage container path"
        key: terraform_storage_container_path
        widget: simple_text
        type: string
        default: "($ project $)/($ environment $)"
    Cycloid-API:
      - name: "Cycloid api login"
        key: api_login
        widget: cy_cred
        type: string
        default: "((basic_auth_cyclobot-account.username))"
      - name: "Cycloid api password"
        key: api_password
        widget: cy_cred
        type: string
        default: "((basic_auth_cyclobot-account.password))"
      - name: "Cycloid api url"
        key: api_url
        widget: simple_text
        type: string
        default: https://http-api.cycloid.io
