# Configuration of the CI pipeline
name: 'Stack validate'
canonical: 'stack-stack-validate'
description: 'Create pipeline to validate stack pipeline, ansible (via molecule) and terraform'
keywords:
  - 'molecule'
  - 'ansible'
  - 'terraform'
  - 'validate'
  - 'pipeline'

author: 'Cycloid'
image: ''
type: 'stack'
config:
  # Configuration of the CI pipeline
  pipeline:
    pipeline:
      path: 'pipeline/pipeline.yml'
    variables:
      path: 'pipeline/variables.sample.yml'
